name: Ambulando
options:
  bundleIdPrefix: com.ambulando
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: en
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  
packages:
  NDKSwift:
    url: https://github.com/pablof7z/NDKSwift.git
    branch: master

targets:
  Ambulando:
    type: application
    platform: iOS
    sources:
      - Sources
    dependencies:
      - package: NDKSwift
        product: NDKSwift
      - package: NDKSwift
        product: NDKSwiftUI
    settings:
      base:
        PRODUCT_NAME: Ambulando
        PRODUCT_BUNDLE_IDENTIFIER: com.ambulando.app
        INFOPLIST_FILE: Sources/Ambulando/Info.plist
        
        # Code Signing Settings - Update these with your values
        DEVELOPMENT_TEAM: "456SHKPP26"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        PROVISIONING_PROFILE_SPECIFIER: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: 5.9
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          DEBUG_INFORMATION_FORMAT: dwarf
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    info:
      path: Sources/Ambulando/Info.plist
      properties:
        CFBundleDisplayName: Ambulando
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        ITSAppUsesNonExemptEncryption: false